language: node_js
node_js:
  - "4"
sudo: false
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  # - npm run semantic-release
notifications:
  email: false
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
